spring:
  profiles:
    active:
    - dev
---
server:
  port: 3355
spring:
  application:
    name: SERVER-DEV
  profiles: dev #开发环境
---
server:
  port: 3356
spring:
  application:
    name: SERVER-TEST
  profiles: dev #测试环境  
